### ISSUE TITLE
Localization "Password:" string

### ISSUE THREAD

**Issue by Survolog** [lxqt/lxqt-policykit#127]
Hello!
When I use tools like partition manager I see lost localization for "Password:"
src/policykit agent gui.ui
```
    <<widget class="QLabel" name="prompt Label">
     <property name="text">
      <string>Password:</string>

```
In src/policykitagentgui.cpp I found
`            promptLabel->setText(text);`
and
```
    if (text != QVariant{})
        prompt Label->setText(text.toString());
```
I dropped that lines and it helps me with localization. But I don't know what I done.
Maybe it will be useful to someone else.

**Comment by tsujan** [comment]
> When I use tools like partition manager I see lost localization for "Password:"

Then, those apps give a non-localized string to the password dialog.

> I dropped that lines...

Those lines say: "Use our (localized) string if no string is given."
