### ISSUE TITLE
Doesn't start as floating window on tiling Wayland compositors

### ISSUE THREAD

**Issue by nonetrix** [lxqt/lxqt-policykit#145]
##### Expected Behavior

The window is floating, likely only requiring you hint to the window manager that it is meant to be floating

##### Current Behavior

It tiles (ignore horrible theming, GTK theme is broken which reminded me to switch more to QT 🥲)
![image](https://github.com/lxqt/lxqt-policykit/assets/45698918/d4dfe602-c8a3-453a-b8c0-2efe297fde41)

##### Possible Solution

Hint that the window should be floating to the compositor, I think this might be done though window class? Might be as simple as changing one line of code

##### Steps to Reproduce (for bugs)

1. Start polkit daemon inside of Hyprland or maybe Sway
2. Do `pkexec echo`
3. Observe that it tiles
4. Make the window floating and resize it
5. Looks correct
6. Repeat ig

##### Context

I am trying to use this inside of Hyprland rather than LXQT, as LXQT is not tiling this doesn't effect it unless a tiling plugin exists. However, it would be more correct to hint that the client should be floating and this works well outside of LXQT since it is fairly minimal program

##### System Information

* Distribution & Version: NixOS 24.11.20240618.c00d587 (Vicuna) x86_64
* Kernel: `Linux nixos 6.9.5 #1-NixOS SMP PREEMPT_DYNAMIC Sun Jun 16 11:51:16 UTC 2024 x86_64 GNU/Linux`
* Qt Version: Not sure?? Perhaps 5.15.14? I think more likely it is some version of QT6. Nix makes it hard to say package build is here though https://github.com/NixOS/nixpkgs/blob/nixos-24.05/pkgs/desktops/lxqt/lxqt-policykit/default.nix same version I am using `ac3af28b5570e60294026d7870978d660cd40328`
* liblxqt Version: 2.0.0
* lxqt-build-tools Version:  2.0.0?
* Package version: 2.0.0

**Comment by nonetrix** [comment]
I think as a work around I might be able to target any applications with title of `Authentication Required` and see Hyprland to float it. Not much to grab the window with besides the title seemingly :/
```
Window 3e360850 -> Authentication Required:
	mapped: 1
	hidden: 0
	at: 967,50
	size: 941,1018
	workspace: 1 (1)
	floating: 0
	pseudo: 0
	monitor: 0
	class: 
	title: Authentication Required
	initialClass: 
	initialTitle: Authentication Required
	pid: 6164
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	tags: 
	swallowing: 0
	focusHistoryID: 1
```

**Comment by stefonarch** [comment]
I'm not aware of a method how apps can tell a compositor they are floating.
I used sway and Hyprland for testing purposes and for some windows rules are needed/better. 
See https://github.com/stefonarch/LXQt-Wayland-files#hyprland-tiling

>other polkit daemons don't have this issue

Examples? I tested `/usr/lib/polkit-kde-authentication-agent-1` in sway and it looks indeed  it's floating by default.

**Comment by nonetrix** [comment]
I don't know exactly but can be done for sure, I didn't set a window true for this
![image](https://github.com/lxqt/lxqt-policykit/assets/45698918/633e479c-c708-497b-a9e8-88c2e412793c)

**Comment by nonetrix** [comment]
I found this
https://github.com/rust-windowing/winit/issues/862#issuecomment-500168711

**Comment by nonetrix** [comment]
This issue seems to have insight, might be better way to do it but seems that setting a low maximum size does the trick:
https://github.com/rust-windowing/winit/issues/862

**Comment by stefonarch** [comment]
Adding fixed window sizes on wayland only because a tiling WM like sway reacts upon that isn't  suitable for sure.

>If anyone is interested, here is the relevant Sway source code for Wayland clients: https://github.com/swaywm/sway/blob/bc258a3be2f946c1c93bcbe40735b2db068e0ea8/sway/desktop/xdg_shell.c#L221-L225
>
>So the only way to force a window to be floating by default, is to set maximum and minimum width (or alternatively height) to the same non-zero value (i.e. make the window non-resizable).
>
>It seems there is no way on Wayland to have a resizable window be floating by default, which is rather unfortunate.

Tiling WM tile windows by design and I think it's upon the user to make float some windows - and there are many of them as you can see in the window rules snippets linked aabove.

**Comment by tsujan** [comment]
Apps don't determine whether a tiling WM shows them tiled or floating; that's up to the WM, whether it's for X11 or Wayland.
